basePath: /api/v1
definitions:
  errors.CustomError:
    properties:
      code:
        type: integer
      internalCode:
        type: string
      message:
        type: string
    type: object
  local.GetLocalsByComunaResponse:
    properties:
      locals:
        items:
          $ref: '#/definitions/model.Local'
        type: array
    type: object
  model.Local:
    properties:
      address:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
host: localhost:1323
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /pharmacy/locals/{commune}:
    get:
      consumes:
      - application/json
      description: obtiene locales al ingresarse una comuna
      operationId: getLocalsByCommune
      parameters:
      - description: Comuna
        in: path
        name: commune
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/local.GetLocalsByComunaResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.CustomError'
      summary: Get locals
      tags:
      - Locals
swagger: "2.0"
